export const SrrET_LOGIN_TRUE = 'SET_LOGIN_TRUE';

export const SET_USER = 'SET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CONCERN_UPDATE = 'CONCERN_UPDATE';
export const UPDATE_QUOTE_OF_THE_DAY = 'UPDATE_QUOTE_OF_THE_DAY';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_JOURNALS = 'ADD_JOURNALS';
export const ADD_BLOGS = 'ADD_BLOGS';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_JOURNAL = 'UPDATE_JOURNAL';
export const UPDATE_SCORE = 'UPDATE_QUIZ_SCORE';
export const RESET_FIRST_TIME_LOGIN = 'RESET_FIRST_TIME_LOGIN';
