export const memeData = [
  {
    ID: 22,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Conspiracy-Keanu.jpg',
    name: 'Conspiracy Keanu',
    rank: 210,
    tags: 'Keanu Reeves, Bill and Ted, Excellent Adventure, Neo',
    topText: 'What If',
  },
  {
    ID: 61,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Sudden-Clarity-Clarence.jpg',
    name: 'Sudden Clarity Clarence',
    rank: 211,
    tags: 'realization, what if, holy shit',
    topText: '',
  },
  {
    ID: 23,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Unpopular-Opinion-Puffin.jpg',
    name: 'Unpopular Opinion Puffin',
    rank: 220,
    tags: 'advice, animal',
    topText: '',
  },
  {
    ID: 24,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Scumbag-Steve.jpg',
    name: 'Scumbag Steve',
    rank: 230,
    tags: 'cap, bad guy, gangsta',
    topText: '',
  },
  {
    ID: 25,
    bottomText: 'And everyone loses their minds',
    image: 'https://imgflip.com/s/meme/And-everybody-loses-their-minds.jpg',
    name: 'Everyone Loses Their Minds',
    rank: 240,
    tags: 'Joker, The Dark Knight, Batman, Heath Ledger',
    topText: '',
  },
  {
    ID: 26,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Picard-Wtf.jpg',
    name: 'Why the F',
    rank: 250,
    tags:
      'Star Trek the Next Generation, TNG, Patrick Stewert, Captain, Annoyed, Jean Luc Picard, Enterprise, Why the Fuck',
    topText: 'Why the F',
  },
  {
    ID: 27,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/10-Guy.jpg',
    name: 'Stoner Stanley',
    rank: 250,
    tags: '10 guy, high, weed, marijuana, stoned',
    topText: '',
  },
  {
    ID: 29,
    bottomText: "Aaaaand It's Gone",
    image: 'http://i.ytimg.com/vi/DNLob2E_Q5s/maxresdefault.jpg',
    name: "Aaaaand It's Gone",
    rank: 260,
    tags: 'And, South Park, Margaritaville',
    topText: '',
  },
  {
    ID: 30,
    bottomText: 'False.',
    image: 'http://www.mememaker.net/static/images/templates/747303.jpg',
    name: 'Schrute Facts',
    rank: 270,
    tags: 'The office, Dwight Schrute, False,',
    topText: '',
  },
  {
    ID: 28,
    bottomText: "And at this point I'm too afraid to ask",
    image: 'https://imgflip.com/s/meme/Afraid-To-Ask-Andy.jpg',
    name: 'Afraid to Ask Andy',
    rank: 270,
    tags: "Andy Dwyer, Chris Pratt, at this point I'm too afraid to ask",
    topText: "I don't know what ___ is",
  },
  {
    ID: 57,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Unhelpful-High-School-Teacher.jpg',
    name: 'Unhelpful High School Teacher',
    rank: 277,
    tags: 'school',
    topText: '',
  },
  {
    ID: 58,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Engineering-Professor.jpg',
    name: 'Engineering Professor',
    rank: 278,
    tags: 'college, no help',
    topText: '',
  },
  {
    ID: 31,
    bottomText: 'I have made a huge mistake',
    image: 'http://i3.kym-cdn.com/photos/images/original/000/847/015/01a.jpg',
    name: 'Minor Mistake Marvin',
    rank: 280,
    tags: 'black kid oven burn realization poker face',
    topText: '',
  },
  {
    ID: 252,
    bottomText: 'Inner Me: ',
    image: 'http://i.imgur.com/AHRz6Rd.jpg',
    name: 'Evil Kermit',
    rank: 281,
    tags: 'kermit, frog, despicable, puppet, green',
    topText: 'Me: ',
  },
  {
    ID: 32,
    bottomText: '',
    image: 'http://images.memes.com/character/meme/facepalm.jpg',
    name: 'Facepalm (Picard)',
    rank: 290,
    tags: 'Jean Luc Picard, Star Trek TNG, Enterprise, Deja !',
    topText: '',
  },
  {
    ID: 33,
    bottomText: '',
    image:
      'http://thefederalistpapers.integratedmarket.netdna-cdn.com/wp-content/uploads/2014/07/Obama-Facepalm.jpg',
    name: 'Facepalm (Obama)',
    rank: 300,
    tags: 'Barack Obama President',
    topText: '',
  },
  {
    ID: 35,
    bottomText: '',
    image: 'https://i.imgflip.com/ae11i.jpg',
    name: 'Facepalm (Putin)',
    rank: 312,
    tags: 'Vladmir Putin Russia President',
    topText: '',
  },
  {
    ID: 34,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/confession-kid.jpg',
    name: 'Confession Kid',
    rank: 320,
    tags: 'facepalm kid, when i was a kid, mistake, silly, stupid',
    topText: '',
  },
  {
    ID: 37,
    bottomText: '',
    image:
      'http://thefw.com/files/2013/03/Screen-Shot-2013-03-06-at-12.02.23-PM.png',
    name: 'Skeptical Baby',
    rank: 340,
    tags: 'cocked eyebrow white baby confused',
    topText: 'You mean to tell me...',
  },
  {
    ID: 113,
    bottomText: "It's Over 9000!",
    image: 'https://i.ytimg.com/vi/DZ7D2g9SUkU/maxresdefault.jpg',
    name: "It's Over 9000",
    rank: 363,
    tags: 'Vegeta, Dragon Ball Z, Saiyan Saga, Power Level',
    topText: '',
  },
  {
    ID: 38,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Third-World-Skeptical-Kid.jpg',
    name: "So you're telling me",
    rank: 370,
    tags: 'Third World Skeptical Kid',
    topText: "So you're telling me",
  },
  {
    ID: 40,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Third-World-Success-Kid.jpg',
    name: 'Third World Success Kid',
    rank: 390,
    tags:
      'dancing tribal child, problems, africa, black kid, overcoming hardships',
    topText: '',
  },
  {
    ID: 39,
    bottomText: 'Too Damn High',
    image: 'http://i0.kym-cdn.com/photos/images/original/000/374/510/b71.jpg',
    name: 'Too Damn High',
    rank: 390,
    tags: 'The Rent is, Jimmy McMillan political slogan',
    topText: '',
  },
  {
    ID: 41,
    bottomText: '',
    image: 'https://imgflip.com/s/meme/Evil-Toddler.jpg',
    name: 'Evil Toddler',
    rank: 400,
    tags: 'laughing child, white kid, prank, mischief, smutty',
    topText: '',
  },
];
